### ISSUE TITLE
Footer links not working

### ISSUE THREAD

**Issue by jeremielp** [mint-metrics/mojito-website#63]
The links "Overview of Mojito" / "Mojito JS library" / "Mojito Storage docs" / "Mojito Analytics docs" are not working.

https://mojito.mx/docs/en/js-delivery-intro
should be
https://mojito.mx/docs/js-delivery-intro

**Comment by kingo55** [comment]
Thanks @jeremielp - good spot.

It looks like the Docusaurus localisation is trying to point users to "English" pages. It's also a good reminder to run another 404 crawl of the docs - I found a couple of others we can fix up too.
